## --- Metadata Options --- ##



# [string] @title       : Name of the game, default: 'SuperGame'.

# [string] @author      : Author of the game, default: 'SuperAuthor'

# [string] @description : Description of the game, default: 'SuperDescription'

# [string] @version     : Version of the game in {major}.{minor}.{revision} format, default: '0.1.0'

# [string] @icon        : Icon path, default: empty string ('')

[metadata]

title = "FridayNightFunkin"

author = "GuglioIsStupid"

description = "3DS Demake of Friday Night Funkin"

version = "0.1.0"

icon = ""



## --- Build Options --- ##



# [bool]   @clean         : Clean the build artifacts and directory before a new build.

#                           This helps reduce chances of cluttering the built data.

#                           Default: false.

#

# [array]  @targts        : Target console(s) to build for. Default: ["ctr", "hac", "cafe"].

#                           These correspond to 3DS, Switch, and Wii U respectively.

#

# [string] @source        : Game source directory; relative to the config

#                           file. Default: "game".

#

[build]

clean = false

targets = ["ctr"]

source = "src"

saveDir = "build"



## --- Debug Options --- ##



# [bool]   @logging       : Whether or not to enable logging. Useful to see what the

#                           application is doing, should it not be working correctly.

[debug]

logging = true

# DO NOT MODIFY #

version = "0.7.0"

# ------------- #